clc; close all; clear

%% Lab4 - Main Script
% Group Participants: 
%   Filip Hesse (4889393)
%   Justin Lee (4885003)
%   Steven Palma (4882385)
%
% NOTE: All the images are created and saved in the 
% /plots folder, which is auto generated by the script. 
% The script does not show them in order to increase 
% runtime and prevent spam.

img_titles = [ "sunflowers.png", "ur_c_s_03a_01_L_0376.png", "ur_c_s_03a_01_L_0377.png", "ur_c_s_03a_01_L_0378.png", "ur_c_s_03a_01_L_0379.png", "ur_c_s_03a_01_L_0380.png","ur_c_s_03a_01_L_0381.png"];
img_titles_cropped = crop_titles(img_titles);

%% Task 1
for i=2:length(img_titles)
    
    img_rgb = imread(char(img_titles(i)));
    img_gray = rgb2gray(img_rgb);
    img_hsv = rgb2hsv(img_rgb);
    
    % Saves the channels of each image
    
    saveimg(img_gray,strcat('1_',img_titles_cropped(i),'_gray'));
    
    for j=1:3
       
       if j==1
           channelrgb='r';
           channelhsv='h';
       elseif j==2
           channelrgb='g';
           channelhsv='s';
       else
           channelrgb='b';
           channelhsv='v';
       end
        
       saveimg(img_rgb(:,:,j),strcat('1_',img_titles_cropped(i),'_rgb_',channelrgb));
       saveimg(img_hsv(:,:,j),strcat('1_',img_titles_cropped(i),'_hsv_',channelhsv));
        
    end
    
    % Segmenting cars
    
    if i==2
        dark_car= img_hsv(390:400,575:595,1);
        mean_dark_car = mean2(dark_car);
        std_dev_dark_car = std2(dark_car);
        up_th = mean_dark_car + std_dev_dark_car;
        low_th = mean_dark_car - std_dev_dark_car;
    end
    
    
    segmentation(img_hsv,img_rgb,img_titles_cropped(i),low_th,up_th,'_DC');
    pause(0.25);
    segmentation(img_hsv,img_rgb,img_titles_cropped(i),0.97,1,'_RC');
    pause(0.25);
    
end

hold off;

%% Task 2

img = imread(char(img_titles(1)));

% characteristic_scale_graph(img,number_scales,initial_sigma,rate_sigma_mult,rate_sigma_sum)
% From lab, 
%number_scales=10, initial_sigma=1, rate_sigma_mult=1.5, rate_sigma_sum=0

% But the graph obtained isnt smooth enough, so it is recommended to call
% the function with the following parameters
% numer_scale=50, initial_sigma=1, rate_sigma_mult=1, rate_sigma_sum=0.5

% It is noticeable slower, but better for the graphs

% [LR_value, C_scale]= characteristic_scale_graph(img,50,1,1,0.5);
[LR_value, C_scale]= characteristic_scale_graph(img,10,1,1.5,0);

disp('For Left Flower')
disp('Characteristic Scale (sigma): ')
disp(C_scale(1))
disp('Value: ')
disp(LR_value(1))

disp('For Right Flower')
disp('Characteristic Scale (sigma): ')
disp(C_scale(2))
disp('Value: ')
disp(LR_value(2))
