clc; close all; clear

%% Lab2 - Main Script
% Group Participants: 
%   Filip Hesse (4889393)
%   Justin Lee (4885003)
%   Steven Palma (4882385)
%
% NOTE: All the images are created and saved in the 
% /plots folder, which is auto generated by the script. 
% The script does not show them in order to increase 
% runtime and prevent spam.

img_titles = [ "i235.png", "tree.png"];
img_titles_cropped = crop_titles(img_titles);

for i= 1:length(img_titles)
    %% Read image
    img = imread(char(img_titles(i)));
    dispAndSaveFig(img, strcat('0_',img_titles_cropped(i)))
    
    %% Task1
    img_title_gauss = strcat(img_titles_cropped(i), '_gauss');
    img_title_saltpepper = strcat(img_titles_cropped(i), '_sp');
    
    img_noisy_gauss      = add_noise_gauss     ( img, strcat('1_',img_title_gauss), 20 ); 
    img_noisy_saltpepper = add_noise_saltpepper( img, strcat('1_',img_title_saltpepper), 0.2 );
   
    %% Task2
    task2_filter(img_noisy_gauss, strcat('2_',img_title_gauss));
    task2_filter(img_noisy_saltpepper, strcat('2_',img_title_saltpepper));
    
    %% Task3
    task3_filter(img, strcat('3_',img_titles_cropped(i)));
    
    %% Task4
    task4_fft(img, strcat('4_',img_titles_cropped(i)));
    
end

