clc; close all; clear

%% Lab6 - Main Script
% Group Participants: 
%   Filip Hesse (4889393)
%   Justin Lee (4885003)
%   Steven Palma (4882385)
%
% NOTE: All the images are created and saved in the 
% /output folder, which is auto generated by the script. 
% The script does not show them in order to increase 
% runtime and prevent spam.


if ~exist('output', 'dir')
   mkdir('output')
end

%Create a vector of two StereoImages (self defined class) containing all
%information about those images, the used points etc.
stereoImages = [StereoImage('Materials/Mire','Mire'), StereoImage('Materials/Rubik','Rubik')];

%Iterate over two images
for stImg=stereoImages
    close all
    
    %% Tasks
    
    % Get the points of each image for the 8-points algorithm
    P1=stImg.getLeftPointsHomogeneous;
    P2=stImg.getRightPointsHomogeneous;
    
    % Get the image matrix of both images
    Im1=stImg.img_left;
    Im2=stImg.img_rigt;
    
    % Task 1: 8 point algorithm function (version1)
    % Get the fundamental matrix
    F = EightPointsAlgorithm(P1, P2);
    disp("Fundamental Matrix (F):");
    disp(F);
    
    
    % Task 2: 8 point algorithm function (version2) (normalized)
    % Get the normalized fundamental matrix
    Fn = EightPointsAlgorithmN(P1, P2);
    disp("Normalized Fundamental Matrix (Fn):");
    disp(Fn);
    
    
    %% Evaluation of the fundamental matrices obtained
    
    % Check the epipolar constraint (x'TFx=0) for version 1
    ec1 = diag(P2'*F*P1)';
    disp("Epipolar Constraint: P2'*F*P1");
    disp(ec1);
    
    % Visualize the epipolar lines for version 1
    visualizeEpipolarLines(Im1,Im2,F,P1(1:2,:)',P2(1:2,:)');
    saveas(gcf,strcat('output/',stImg.title,'epipolarlines.png'));
    
    disp("Press any key to continue!");
    pause;
    
    % Check the epipolar normalized constraint (x'TFnx=0) for version 2
    ec2 = diag(P2'*Fn*P1)';
    disp("Epipolar Normalized Constraint: P2'*Fn*P1");
    disp(ec2);
    
    % Visualize the normalized epipolar lines for version 2
    visualizeEpipolarLines(Im1,Im2,Fn,P1(1:2,:)',P2(1:2,:)');
    saveas(gcf,strcat('output/',stImg.title,'epipolarlinesnormalized.png'));
    
    disp("Press any key to continue!");
    pause;
    
    % Check the epipoles
    [U,W,V]=svd(F);
    epl=U(:,size(U,2))';
    epr=V(:,size(V,2))';
    disp("Epipoles:")
    disp(epl);
    disp(epr);
    
    [Un,Wn,Vn]=svd(Fn);
    epln=Un(:,size(Un,2))';
    eprn=Vn(:,size(Vn,2))';
    disp("Normalized Epipoles:")
    disp(epln);
    disp(eprn);
    
    disp("Press any key to continue!");
    pause;
    
end

close all;